[package]
name = "ton_onchain_minecraft"
description = "Minecraft-like on-chain voxel world on TON"
version = "0.1.0"
license = "MIT"

[toolchain]
acton = "1.0.0"

[contracts.Empty]
display-name = "Empty"
src = "contracts/src/Empty.tolk"
depends = []

[test]

[fmt]
width = 100
ignore = []

[scripts]
deploy-emulation = "acton script contracts/scripts/deploy.tolk"
deploy-testnet = "acton script contracts/scripts/deploy.tolk --net testnet"

[import-mappings]
acton = ".acton"
contracts = "contracts/src"
gen = "gen"
tests = "contracts/tests"
wrappers = "contracts/wrappers"

# Check full Acton.toml reference and all available keys:
# https://ton-blockchain.github.io/acton/docs/acton-toml
